/*This code is generated by an tool, changes to it may be overriten.*/ 
define([], function() { 
  return ["$templateCache", function($templateCache) {
  'use strict';

  $templateCache.put('content/views/home.html',
    "Home {{message}} <a href=\"#/test\">Go to Test</a>"
  );


  $templateCache.put('content/views/test.html',
    "Test {{value}} <a href=\"#/\">Go to Home</a>"
  );
  }];
});