/*This code is generated by an tool, changes to it may be overriten.*/ 
define([], function() { 
  return ["$templateCache", function($templateCache) {
  'use strict';

  $templateCache.put('content/views/home.html',
    "Home {{message}} <a class=\"btn btn-default\" href=\"#/test\">Go to Test</a> <a href=\"#\" class=\"thumbnail\"><img src=\"/content/img/mountains-fog-green-beauty.jpg\"></a>"
  );


  $templateCache.put('content/views/test.html',
    "Test {{value}} <a class=\"btn btn-default\" href=\"#/\">Go to Home</a>"
  );
  }];
});